### ISSUE TITLE
[RFC]: Drop reCaptcha Mailhide

### ISSUE THREAD

**Issue by ghostwriter** [laminas/laminas-recaptcha#19]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 3.5.x  |
| BC Break?           | Yes|

### Goal

Drop reCaptcha Mailhide

### Background

reCaptcha Mailhide was deprecated on March 31, 2018.

### Considerations

There are [packages](https://packagist.org/packages/laminas/laminas-recaptcha/dependents) that rely on this package for the Captcha (not Mailhide):

https://packagist.org/packages/laminas/laminas-form
https://packagist.org/packages/laminas/laminas-captcha

### Proposal(s)

Remove `Mailhide.php`, `MailHideException.php` & `MailhideTest.php`

### Appendix

If accepted, we can close #20

**Comment by Ocramius** [comment]
Should be done in a major release anyway.

**Comment by gsteel** [comment]
Auto closed in #28 but still needs doing for 4.0

**Comment by Ocramius** [comment]
There won't be a `4.0` though

**Comment by gsteel** [comment]
Oh good!
